// lib/data.ts

export const team = [
  {
    name: "Aurélie Soanimino Radomiarisoa épouse Picot",
    role: "Fondatrice et Présidente",
    bio: "Originaire de Toamasina (Madagascar) et résidant à Pau, elle est à l'origine du projet Zaza Midôla depuis sa première édition en 2022.",
    photo: "https://picsum.photos/seed/zaza-aurelie/480/480",
  },
  {
    name: "Christophe Picot",
    role: "Trésorier",
    bio: "Présent depuis le début de cette aventure, il apporte son soutien moral, sa confiance et son aide financière qui participent activement à la réalisation des projets de l'association.",
    photo: "/equipes/picot.jpg",
  },
  {
    name: "Yves Rosati",
    role: "Secrétaire",
    bio: "Passionné de football et fidèle soutien de l'association, il contribue au développement du projet grâce à son accompagnement, ses conseils et son réseau.",
    photo: "/equipes/rosati.jpg",
  },
  {
    name: "Josinie",
    role: "Restaurant Ninie Soupe — Toamasina",
    bio: "À chaque édition du tournoi, elle prépare avec son équipe les repas destinés aux enfants participants et à leurs éducateurs, dans une ambiance chaleureuse et conviviale.",
    photo: "/equipes/josinie.jpg",
  },
  {
    name: "Tonton Solo & Madame Simonelle",
    role: "Organisation sur le terrain",
    bio: "Ils consacrent beaucoup de temps et d'énergie à la préparation du tournoi : infrastructures sportives et démarches administratives sur place à Toamasina.",
    photo: "https://picsum.photos/seed/zaza-solo/480/480",
  },
  {
    name: "Les bénévoles",
    role: "France & Madagascar",
    bio: "Ils participent à l'organisation des événements et aux actions solidaires, en France comme à Madagascar.",
    photo: "/benevoles/benevoles.png",
  },
];

export const supporters = [
  {
    name: "Patrick Cazaux",
    role: "Gravoplast Pau",
    bio: "Depuis la première édition du tournoi, il accompagne l'association avec générosité en réalisant et offrant les médailles, trophées, coupes et gravures destinés aux jeunes participants.",
    photo: "https://picsum.photos/seed/zaza-patrick/400/400",
  },
  {
    name: "Christophe Picot",
    role: "Soutien financier",
    bio: "Présent depuis le début de cette aventure, il apporte son soutien moral, sa confiance et son aide financière.",
    photo: "/equipes/picot.jpg",
  },
  {
    name: "Yves Rosati",
    role: "Conseils & réseau",
    bio: "Passionné de football et fidèle soutien de l'association, il contribue au développement du projet grâce à son accompagnement.",
    photo: "/equipes/rosati.jpg",
  },
];

export const values = [
  {
    title: "Solidarité",
    text: "Aider ceux qui en ont besoin, sans distinction.",
  },
  {
    title: "Respect",
    text: "Respect des enfants, des éducateurs, des familles et des bénévoles.",
  },
  {
    title: "Partage",
    text: "Créer des moments de rencontre et de fraternité.",
  },
  {
    title: "Espoir",
    text: "Permettre aux enfants de croire en leurs rêves.",
  },
];

export const timeline = [
  {
    year: "2022",
    title: "Première édition",
    text: "Un cadeau d'anniversaire devient une aventure humaine : naissance du tournoi à Toamasina.",
  },
  {
    year: "2024",
    title: "Deuxième édition",
    text: "Face au succès de la première édition, le tournoi revient avec encore plus d'enfants et de bénévoles.",
  },
  {
    year: "30 juillet 2025",
    title: "Création de l'association",
    text: "Zaza Midôla devient officiellement une association (RNA : W643013903) pour pérenniser le projet.",
  },
  {
    year: "Déc. 2026",
    title: "Troisième édition",
    text: "Une nouvelle édition se prépare, avec toujours plus d'ambition solidaire.",
  },
];

export const stats = [
  { value: "3", label: "éditions du tournoi" },
  { value: "2022", label: "année de création" },
  { value: "100%", label: "bénévole" },
  { value: "2", label: "pays mobilisés" },
];

export const galleryImages = [
  { src: "/gallery/1.jfif", alt: "Photo du tournoi Zaza Midôla 1" },
  { src: "/gallery/2.jfif", alt: "Photo du tournoi Zaza Midôla 2" },
  { src: "/gallery/3.jfif", alt: "Photo du tournoi Zaza Midôla 3" },
  { src: "/gallery/4.jfif", alt: "Photo du tournoi Zaza Midôla 4" },
  { src: "/gallery/5.jfif", alt: "Photo du tournoi Zaza Midôla 5" },
  { src: "/gallery/6.jfif", alt: "Photo du tournoi Zaza Midôla 6" },
  { src: "/gallery/7.jfif", alt: "Photo du tournoi Zaza Midôla 7" },
  { src: "/gallery/8.jfif", alt: "Photo du tournoi Zaza Midôla 8" },
  { src: "/gallery/9.jfif", alt: "Photo du tournoi Zaza Midôla 9" },
  { src: "/gallery/10.jfif", alt: "Photo du tournoi Zaza Midôla 10" },
  { src: "/gallery/11.jfif", alt: "Photo du tournoi Zaza Midôla 11" },
  { src: "/gallery/12.jfif", alt: "Photo du tournoi Zaza Midôla 12" },
  { src: "/gallery/13.jfif", alt: "Photo du tournoi Zaza Midôla 13" },
  { src: "/gallery/14.jfif", alt: "Photo du tournoi Zaza Midôla 14" },
  { src: "/gallery/15.jfif", alt: "Photo du tournoi Zaza Midôla 15" },
  { src: "/gallery/16.jfif", alt: "Photo du tournoi Zaza Midôla 16" },
  { src: "/gallery/17.jfif", alt: "Photo du tournoi Zaza Midôla 17" },
  { src: "/gallery/18.jfif", alt: "Photo du tournoi Zaza Midôla 18" },
  { src: "/gallery/19.jfif", alt: "Photo du tournoi Zaza Midôla 19" },
  { src: "/gallery/20.jfif", alt: "Photo du tournoi Zaza Midôla 20" },
  { src: "/gallery/21.jfif", alt: "Photo du tournoi Zaza Midôla 21" },
  { src: "/gallery/22.jfif", alt: "Photo du tournoi Zaza Midôla 22" },
  { src: "/gallery/23.jfif", alt: "Photo du tournoi Zaza Midôla 23" },
  { src: "/gallery/24.jfif", alt: "Photo du tournoi Zaza Midôla 24" },
  { src: "/gallery/25.jfif", alt: "Photo du tournoi Zaza Midôla 25" },
  { src: "/gallery/26.jfif", alt: "Photo du tournoi Zaza Midôla 26" },
  { src: "/gallery/27.jfif", alt: "Photo du tournoi Zaza Midôla 27" },
  { src: "/gallery/28.jfif", alt: "Photo du tournoi Zaza Midôla 28" },
  { src: "/gallery/29.jfif", alt: "Photo du tournoi Zaza Midôla 29" },
  { src: "/gallery/30.jfif", alt: "Photo du tournoi Zaza Midôla 30" },
  { src: "/gallery/31.jfif", alt: "Photo du tournoi Zaza Midôla 31" },
  { src: "/gallery/32.jfif", alt: "Photo du tournoi Zaza Midôla 32" },
  { src: "/gallery/33.jfif", alt: "Photo du tournoi Zaza Midôla 33" },
  { src: "/gallery/34.jfif", alt: "Photo du tournoi Zaza Midôla 34" },
  { src: "/gallery/35.jfif", alt: "Photo du tournoi Zaza Midôla 35" },
  { src: "/gallery/36.jfif", alt: "Photo du tournoi Zaza Midôla 36" },
  { src: "/gallery/37.jfif", alt: "Photo du tournoi Zaza Midôla 37" },
  { src: "/gallery/38.jfif", alt: "Photo du tournoi Zaza Midôla 38" },
  { src: "/gallery/39.jfif", alt: "Photo du tournoi Zaza Midôla 39" },
  { src: "/gallery/40.jfif", alt: "Photo du tournoi Zaza Midôla 40" },
  { src: "/gallery/41.jfif", alt: "Photo du tournoi Zaza Midôla 41" },
  { src: "/gallery/42.jfif", alt: "Photo du tournoi Zaza Midôla 42" },
  { src: "/gallery/43.jfif", alt: "Photo du tournoi Zaza Midôla 43" },
  { src: "/gallery/44.jfif", alt: "Photo du tournoi Zaza Midôla 44" },
  { src: "/gallery/45.jfif", alt: "Photo du tournoi Zaza Midôla 45" },
  { src: "/gallery/46.jfif", alt: "Photo du tournoi Zaza Midôla 46" },
  { src: "/gallery/47.jfif", alt: "Photo du tournoi Zaza Midôla 47" },
  { src: "/gallery/48.jfif", alt: "Photo du tournoi Zaza Midôla 48" },
  { src: "/gallery/49.jfif", alt: "Photo du tournoi Zaza Midôla 49" },
  { src: "/gallery/50.jfif", alt: "Photo du tournoi Zaza Midôla 50" },
  { src: "/gallery/51.jfif", alt: "Photo du tournoi Zaza Midôla 51" },
  { src: "/gallery/52.jfif", alt: "Photo du tournoi Zaza Midôla 52" },
  { src: "/gallery/53.jfif", alt: "Photo du tournoi Zaza Midôla 53" },
  { src: "/gallery/54.jfif", alt: "Photo du tournoi Zaza Midôla 54" },
  { src: "/gallery/55.jfif", alt: "Photo du tournoi Zaza Midôla 55" },
  { src: "/gallery/56.jfif", alt: "Photo du tournoi Zaza Midôla 56" },
  { src: "/gallery/57.jfif", alt: "Photo du tournoi Zaza Midôla 57" },
  { src: "/gallery/58.jfif", alt: "Photo du tournoi Zaza Midôla 58" },
  { src: "/gallery/59.jfif", alt: "Photo du tournoi Zaza Midôla 59" },
  { src: "/gallery/60.jfif", alt: "Photo du tournoi Zaza Midôla 60" },
  { src: "/gallery/61.jfif", alt: "Photo du tournoi Zaza Midôla 61" },
  { src: "/gallery/62.jfif", alt: "Photo du tournoi Zaza Midôla 62" },
  { src: "/gallery/63.jfif", alt: "Photo du tournoi Zaza Midôla 63" },
  { src: "/gallery/64.jfif", alt: "Photo du tournoi Zaza Midôla 64" },
  { src: "/gallery/65.jfif", alt: "Photo du tournoi Zaza Midôla 65" },
  { src: "/gallery/66.jfif", alt: "Photo du tournoi Zaza Midôla 66" },
  { src: "/gallery/67.jfif", alt: "Photo du tournoi Zaza Midôla 67" },
  { src: "/gallery/68.jfif", alt: "Photo du tournoi Zaza Midôla 68" },
  { src: "/gallery/69.jfif", alt: "Photo du tournoi Zaza Midôla 69" },
  { src: "/gallery/70.jfif", alt: "Photo du tournoi Zaza Midôla 70" },
  { src: "/gallery/71.jfif", alt: "Photo du tournoi Zaza Midôla 71" },
  { src: "/gallery/72.jfif", alt: "Photo du tournoi Zaza Midôla 72" },
  { src: "/gallery/73.jfif", alt: "Photo du tournoi Zaza Midôla 73" },
  { src: "/gallery/74.jfif", alt: "Photo du tournoi Zaza Midôla 74" },
  { src: "/gallery/75.jfif", alt: "Photo du tournoi Zaza Midôla 75" },
  { src: "/gallery/76.jfif", alt: "Photo du tournoi Zaza Midôla 76" },
  { src: "/gallery/77.jfif", alt: "Photo du tournoi Zaza Midôla 77" },
  { src: "/gallery/78.jfif", alt: "Photo du tournoi Zaza Midôla 78" },
  { src: "/gallery/79.jfif", alt: "Photo du tournoi Zaza Midôla 79" },
  { src: "/gallery/80.jfif", alt: "Photo du tournoi Zaza Midôla 80" },
  { src: "/gallery/81.jfif", alt: "Photo du tournoi Zaza Midôla 81" },
  { src: "/gallery/82.jfif", alt: "Photo du tournoi Zaza Midôla 82" },
];